### ISSUE TITLE
Интеграция в MajorDoMo

### ISSUE THREAD

**Issue by Djeday999** [alryaz/hass-energosbyt-plus#7]
Здравствуйте! Есть возможность реализовать такое в MajorDoMo?

**Comment by alryaz** [comment]
Здравствуйте!

Не планировалось, так как данная платформа не используется в моём быту, поэтому, к сожалению, осваивать ее будет довольно затратно.

Тем не менее, вся работа с API специально выведена в отдельный пакет Python, и, в теории, желающие могут воспользоваться наработками для перевода функционала (уже на язык PHP).
